version: '3.8'
services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URI=${REDIS_URI}
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - education-forge-network
    depends_on:
      - db
  cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --logLevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - education-forge-network
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - education-forge-network
networks:
  education-forge-network:
    driver: bridge
volumes:
  cache:
    driver: local
  db:
    driver: local
